version: '3.4'

services:
  calculomonetarioapi:
    image: ${DOCKER_REGISTRY-}calculomonetarioapi
    container_name: calculomonetarioaApi
    build:
      context: .
      dockerfile: CalculoMonetarioApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo 
    ports:
        - "44324:80"
    networks:
      - calculoMonetarioApi-network
    environment:
      - ASPNETCORE_ENVIRONMENT= "Development",
      - TAXA_JUROS= "0.01",
      - URI_JUROS= calculoMonetarioApi-network/taxaJuros,
      - BASE_URL_GITHUB= "https://api.github.com",
      - USUARIO_PADRAO= "tiago-system13",
      - NOME_REPOSITORIO"= "CalculoMonetarioApi"

networks:
  calculoMonetarioApi-network:
    driver: bridge