version: '3.4'

services:
  calculomonetarioapi:
    image: ${DOCKER_REGISTRY-}calculomonetarioapi
    build:
      context: .
      dockerfile: CalculoMonetarioApi/Dockerfile
    ports:
          - "44331:80"
