version: '3.4'

services:
  calculomonetarioapi:
    image: ${DOCKER_REGISTRY-}calculomonetarioapi
    container_name: calculomonetarioaApi
    build:
      context: .
      dockerfile: CalculoMonetarioApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo  
      ASPNETCORE_ENVIRONMENT: "Development"
      TAXA_JUROS: "0,01"
      URI_JUROS: http://calculomonetarioapi2/taxajuros
      BASE_URL_GITHUB: https://api.github.com
      USUARIO_PADRAO: "tiago-system13"
      NOME_REPOSITORIO: "CalculoMonetarioApi"
    ports:
        - "44324:80"
    depends_on:
        - calculomonetarioapi2 
      
  calculomonetarioapi2:
    image: ${DOCKER_REGISTRY-}calculomonetarioapi2
    container_name: calculomonetarioaApi2
    build:
      context: .
      dockerfile: CalculoMonetarioApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: "Development"
      TAXA_JUROS: "0,01"
    ports:
        - "44326:80"
   